apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cybersnare

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - decision.yaml
  - logger.yaml
  - gnn-scorer.yaml
  - deception-pod.yaml
  - workloads.yaml
  - network-policies.yaml
