apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cybersnare-events
  namespace: cybersnare
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cybersnare-zeek
  namespace: cybersnare
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cybersnare-manifests
  namespace: cybersnare
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
